services:
    vereinskalender:
        container_name: vereinskalender-app
        image: verein-cal:dev
        build:
            context: .
            dockerfile: .docker/Dockerfile
        ports:
            - '8443:443'
        environment:
            - DB_SERVER=db
            - DB_USERNAME=verein
            - DB_PASSWORD=verein
            - DB_PORT=3306
            - TZ=Europe/Berlin
        depends_on:
            - db
        restart: unless-stopped

    db:
        container_name: vereinskalender-mysql
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: vereinskalender
            MYSQL_USER: verein
            MYSQL_PASSWORD: verein
            TZ: Europe/Berlin
        healthcheck:
            test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
            start_period: 10s
            interval: 10s
            timeout: 5s
            retries: 3
        volumes:
            - ./mysql:/var/lib/mysql
        restart: unless-stopped
    
    # Optional (für Debugging / Entwicklung)
    phpmyadmin:
        container_name: vereinskalender-phpmyadmin
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - '8090:80'
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: verein
            MYSQL_PASSWORD: verein
        depends_on:
            - db
        restart: unless-stopped
